[z/OS] Add --no-parallel option to Makefile.
Resolves missing multiprocessing in python on z/OS.
ImportError: This platform lacks a functioning sem_open implementation,
therefore, the required synchronization primitives needed will not
function, see issue 3770.